language: java
jdk:
  - openjdk11
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid

script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-heroku,deploy-docker

#deploy:
#  provider: heroku
#  api-key:
#    secure: "<HEROKU_API_KEY>"
#  app: <YOUR_HERKU_APP_NAME>
